// OpenAI API integration for PR checklist generation
import type { PRAnalysisResult, PRData } from '@src/types';
import OpenAI from 'openai';

export interface OpenAIConfig {
  apiKey: string;
  model: string;
  apiEndpoint?: string;
}

class OpenAIClient {
  private client: OpenAI;
  private model: string;

  constructor(config: OpenAIConfig) {
    this.client = new OpenAI({
      apiKey: config.apiKey,
      baseURL: config.apiEndpoint,
      dangerouslyAllowBrowser: true, // Add this flag to allow browser usage
    });
    this.model = config.model || 'gpt-4-turbo';
  }

  /**
   * Analyze a PR and generate checklist and summary
   */
  async analyzePR(prData: PRData, languageOverride?: string): Promise<PRAnalysisResult> {
    try {
      // Get language preference from storage or use override if provided
      const language = languageOverride || (await languagePreferenceStorage.get()) || navigator.language || 'en';

      console.log(`Using language for analysis: ${language}`);
      const prompt = this.buildPRAnalysisPrompt(prData, language);
      const response = await this.callOpenAI(prompt);
      return this.parseAnalysisResponse(response);
    } catch (error) {
      console.error('Error analyzing PR with OpenAI:', error);
      throw new Error('Failed to analyze PR with OpenAI');
    }
  }

  /**
   * Build the prompt for PR analysis with language preference
   */
  private buildPRAnalysisPrompt(prData: PRData, language: string = 'en'): string {
    // Format the PR data for the prompt
    const { title, description, files } = prData;

    // List of changed files with stats and patches
    const fileChanges = files
      .map((file: any) => {
        return `
File: ${file.filename} (${file.status})
Changes: +${file.additions} -${file.deletions}
${file.patch ? `Patch:\n${file.patch}` : 'No patch available'}
`;
      })
      .join('\n---\n');

    // Determine output language based on browser's language setting
    const outputLanguage = language.startsWith('ja') ? 'Japanese' : language.startsWith('ko') ? 'Korean' : 'English';

    // Construct the full prompt with language instruction
    return `
Analyze this pull request and provide your response in ${outputLanguage}. Include:
1. A summary of the PR, including:
   - Background
   - Problem being solved
   - Solution approach
   - Implementation details

2. For each changed file, create a checklist of specific items to review, focusing on:
   - Code correctness
   - Best practices
   - Potential bugs
   - Performance concerns
   - Security implications

PR Title: ${title}
PR Description: ${description}

Changed Files:
${fileChanges}

Format your response as a JSON object with the following structure:
{
  "summary": {
    "background": "...",
    "problem": "...",
    "solution": "...",
    "implementation": "..."
  },
  "fileChecklists": [
    {
      "id": "file-1",
      "filename": "path/to/file.ts",
      "explanation": "Update the checklist for this file generated by OpenAI",
      "checklistItems": [
        {
          "id": "item-1",
          "description": "Check that...",
          "status": "PENDING"
        },
        ...more items
      ]
    },
    ...more files
  ]
}

Important: All text content inside the JSON must be in ${outputLanguage}. Keep the JSON structure and field names in English.
`;
  }

  /**
   * Make the API call to OpenAI
   */
  private async callOpenAI(prompt: string): Promise<string> {
    try {
      const response = await this.client.chat.completions.create({
        model: this.model,
        messages: [
          {
            role: 'system',
            content:
              'You are a senior software developer conducting a thorough code review. You provide detailed, actionable feedback in JSON format as requested.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: 0.3,
        response_format: { type: 'json_object' },
      });

      return response.choices[0].message.content || '';
    } catch (error) {
      console.error('Error calling OpenAI API:', error);
      throw error;
    }
  }

  /**
   * Parse the OpenAI response into a structured format
   */
  private parseAnalysisResponse(responseText: string): PRAnalysisResult {
    try {
      // Parse the JSON response
      const parsedResponse = JSON.parse(responseText);

      // Ensure all file checklist items have IDs
      const fileChecklists = parsedResponse.fileChecklists.map((fileChecklist: any) => ({
        ...fileChecklist,
        checklistItems: fileChecklist.checklistItems.map((item: any, index: number) => ({
          id: item.id || `${fileChecklist.filename}-item-${index}`,
          description: item.description,
          status: item.status || 'PENDING',
        })),
      }));

      return {
        summary: parsedResponse.summary,
        fileChecklists,
      };
    } catch (error) {
      console.error('Error parsing OpenAI response:', error);
      throw new Error('Failed to parse OpenAI response');
    }
  }
}

// Storage for OpenAI API key
export const openaiApiKeyStorage = {
  get: async (): Promise<string | null> => {
    try {
      const result = await chrome.storage.local.get('openaiApiKey');
      return result.openaiApiKey || null;
    } catch (error) {
      console.error('Error getting OpenAI API key:', error);
      return null;
    }
  },

  set: async (apiKey: string): Promise<void> => {
    try {
      await chrome.storage.local.set({ openaiApiKey: apiKey });
    } catch (error) {
      console.error('Error setting OpenAI API key:', error);
      throw error;
    }
  },

  clear: async (): Promise<void> => {
    try {
      await chrome.storage.local.remove('openaiApiKey');
    } catch (error) {
      console.error('Error clearing OpenAI API key:', error);
      throw error;
    }
  },
};

// Storage for language preference
export const languagePreferenceStorage = {
  get: async (): Promise<string | null> => {
    try {
      const result = await chrome.storage.local.get('languagePreference');
      return result.languagePreference || null;
    } catch (error) {
      console.error('Error getting language preference:', error);
      return null;
    }
  },

  set: async (language: string): Promise<void> => {
    try {
      await chrome.storage.local.set({ languagePreference: language });
    } catch (error) {
      console.error('Error setting language preference:', error);
      throw error;
    }
  },

  clear: async (): Promise<void> => {
    try {
      await chrome.storage.local.remove('languagePreference');
    } catch (error) {
      console.error('Error clearing language preference:', error);
      throw error;
    }
  },
};

// Create and export OpenAI client instance
export const createOpenAIClient = async (): Promise<OpenAIClient | null> => {
  const apiKey = await openaiApiKeyStorage.get();
  if (!apiKey) {
    return null;
  }

  return new OpenAIClient({
    apiKey,
    model: 'gpt-4-turbo',
  });
};

export default OpenAIClient;
